/**
 * MIT License
 * Copyright (c) 2022 Andrew Hovey
 * Full License Text: https://ahovey.com/MITLicense.html
 * The above abbreviated copyright notice shall be included in all copies or substantial portions of the Software.
 */

@isTest
public without sharing class DeleteEmptyFolders_Test {

    /* USELESS TEST CLASS! I haven't had time to write a proper one. */
    @isTest
    static void runTest() {
        new DeleteEmptyFolders().processEmptyFolders(true);
    }
}